fix

diff --git a/.github/workflows/test-suite.yml b/.github/workflows/test-suite.yml
--- a/.github/workflows/test-suite.yml
+++ b/.github/workflows/test-suite.yml
@@ -310,50 +310,53 @@ jobs:
         with:
           name: bare-expo-android-builds
           path: apps/bare-expo/android/app/build/outputs/apk/release
-      - name: 🍺 Install Maestro
-        run: |
-          curl -Ls "https://get.maestro.mobile.dev" | bash
-          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
-      - name: ♻️ Restore caches
-        uses: ./.github/actions/expo-caches
-        id: expo-caches
-        with:
-          yarn-workspace: 'true'
-      - name: 🧶 Install node modules in root dir
-        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
-        run: yarn install --frozen-lockfile
-      - name: 🧶 Install image comparison server node modules
-        run: yarn install --frozen-lockfile
-        working-directory: apps/bare-expo/e2e/image-comparison
-      - name: 🧪 Run e2e tests (bare-expo)
-        uses: ./.github/actions/use-android-emulator
-        with:
-          avd-api: ${{ matrix.api-level }}
-          avd-name: avd-${{ matrix.api-level }}
-          script: |
-            # Start image comparison server (needs adb from use-android-emulator)
-            mkdir -p ~/.maestro/tests
-            ./e2e/image-comparison/src/server.ts > ~/.maestro/tests/screenshot-server-logs 2>&1 &
-            echo $! > /tmp/image-server.pid
-            # Run the actual tests
-            ./scripts/start-android-e2e-test.ts --test
-          working-directory: ./apps/bare-expo
-      - name: 📸 Store testing artifacts
-        if: always()
-        id: upload-artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: bare-expo-artifacts-android
-          path: |
-            ~/.maestro/tests/**/*
-          overwrite: true
+      - name: test
+        run: exit 1
+      # - name: 🍺 Install Maestro
+      #   run: |
+      #     curl -Ls "https://get.maestro.mobile.dev" | bash
+      #     echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
+      # - name: ♻️ Restore caches
+      #   uses: ./.github/actions/expo-caches
+      #   id: expo-caches
+      #   with:
+      #     yarn-workspace: 'true'
+      # - name: 🧶 Install node modules in root dir
+      #   if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
+      #   run: yarn install --frozen-lockfile
+      # - name: 🧶 Install image comparison server node modules
+      #   run: yarn install --frozen-lockfile
+      #   working-directory: apps/bare-expo/e2e/image-comparison
+      # - name: 🧪 Run e2e tests (bare-expo)
+      #   uses: ./.github/actions/use-android-emulator
+      #   with:
+      #     avd-api: ${{ matrix.api-level }}
+      #     avd-name: avd-${{ matrix.api-level }}
+      #     script: |
+      #       # Start image comparison server (needs adb from use-android-emulator)
+      #       mkdir -p ~/.maestro/tests
+      #       ./e2e/image-comparison/src/server.ts > ~/.maestro/tests/screenshot-server-logs 2>&1 &
+      #       echo $! > /tmp/image-server.pid
+      #       # Run the actual tests
+      #       ./scripts/start-android-e2e-test.ts --test
+      #     working-directory: ./apps/bare-expo
+      # - name: 📸 Store testing artifacts
+      #   if: always()
+      #   id: upload-artifacts
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: bare-expo-artifacts-android
+      #     path: |
+      #       ~/.maestro/tests/**/*
+      #     overwrite: true
       - name: 🔗 Artifacts download URL
         if: always()
         run: |
           echo "Artifacts URL: ${{ steps.upload-artifacts.outputs.artifact-url }}"
       - name: 🔔 Notify on Slack
         uses: ./.github/actions/slack-notify
-        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
+        # if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
+        if: failure()
         with:
           webhook: ${{ secrets.slack_webhook_android }}
           channel: '#expo-android'
